apiVersion: v1
kind: List
items:
  - kind: Namespace
    apiVersion: v1
    metadata:
      name: instana-agent
      labels:
        name: instana-agent

  - apiVersion: v1
    kind: Secret
    metadata:
      name: instana-agent-secret
      namespace: instana-agent
    data:
      key: {{BASE64_ENCODED_INSTANA_KEY}}

  - apiVersion: extensions/v1beta1
    kind: DaemonSet
    metadata:
      labels:
        app: instana-agent
      name: instana-agent
      namespace: instana-agent
    spec:
      template:
        metadata:
          labels:
            app: instana-agent
        spec:
          hostIPC: true
          hostNetwork: true
          hostPID: true
          containers:
            - name: instana-agent
              image: instana/agent
              imagePullPolicy: Always
              env:
                - name: INSTANA_HOST
                  value: {{INSTANA_HOST}}
                - name: INSTANA_PORT
                  value: '{{INSTANA_PORT}}'
                - name: INSTANA_KEY
                  valueFrom:
                    secretKeyRef:
                      name: instana-agent-secret
                      key: key
              securityContext:
                privileged: true
              volumeMounts:
                - name: dev
                  mountPath: /dev
                - name: run
                  mountPath: /var/run/docker.sock
                - name: sys
                  mountPath: /sys
                - name: log
                  mountPath: /var/log
          volumes:
            - name: dev
              hostPath:
                  path: /dev
            - name: run
              hostPath:
                  path: /var/run/docker.sock
            - name: sys
              hostPath:
                  path: /sys
            - name: log
              hostPath:
                  path: /var/log